// Generated by CoffeeScript 1.10.0
module.exports = function(grunt) {
  'use strict';
  var PORT, path, projectRoot, webpack;
  require('load-grunt-tasks')(grunt);
  path = require('path');
  webpack = require('webpack');
  projectRoot = path.resolve(__dirname, '../');
  PORT = 9008;
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    execute: {
      target: {
        src: ['server.js']
      }
    },
    clean: {
      all: {
        src: ["build/**/*"]
      }
    },
    watch: {
      less: {
        files: 'src/styles/**/*.less',
        tasks: ['less']
      }
    }
  });
  grunt.registerTask('default', ['execute']);
};
